version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user-abc
      POSTGRES_PASSWORD: password-1234
      POSTGRES_DB: my-postgres-db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
